# Liquid War is a multiplayer wargame
# Copyright (C) 1998-2018 Christian Mauduit
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# Liquid War homepage : https://ufoot.org/liquidwar/v5
# Contact author      : ufoot@ufoot.org

FROM debian
MAINTAINER Christian Mauduit "ufoot@ufoot.org"
LABEL package="liquidwar" version="@VERSION@" org.ufoot.liquidwar.os="debian" org.ufoot.liquidwar.type="server" description="Liquid War server image, contains a running instance of the program, listening on default port 8035. Homepage https://ufoot.org/liquidwar/v5"

ENV DEBIAN_FRONTEND noninteractive
RUN (apt-get update && apt-get upgrade -y -q && apt-get dist-upgrade -y -q && apt-get -y -q autoclean && apt-get -y -q autoremove)

# minimal build requirements
RUN apt-get install -y -q gcc make liballegro4-dev
RUN apt-get clean

# our build
RUN install -d /usr/local/src
COPY liquidwar-@VERSION@.tar.gz /usr/local/src/liquidwar-@VERSION@.tar.gz
RUN cd /usr/local/src && tar xzf liquidwar-@VERSION@.tar.gz
RUN cd /usr/local/src/liquidwar-@VERSION@ && ./configure && make && make install

# run server on default port
EXPOSE 8035
USER nobody
ENTRYPOINT /usr/local/bin/liquidwar-server -2 -public -comment Public_Liquid_War_5_server_running_in_Docker_instance


